### ISSUE TITLE
finance table 데이터 손실

### ISSUE THREAD

**Issue by Jinseok-Heo** [economicus/finance_data#10]
[2022-02-16 00:09] : (no_files, None) #2474 / 2491 rows > REPLACE INTO finance (99.31754315535929 %)[OK]
[Errno 2] No such file or directory: 'quarter_fs/224020.csv' : 224020
object of type 'NoneType' has no len()
[2022-02-16 00:09] : (no_files, None) #2475 / 2491 rows > REPLACE INTO finance (99.35768767563228 %)[OK]
[Errno 2] No such file or directory: 'quarter_fs/207490.csv' : 207490
object of type 'NoneType' has no len()
[2022-02-16 00:09] : (no_files, None) #2476 / 2491 rows > REPLACE INTO finance (99.39783219590525 %)[OK]
[Errno 2] No such file or directory: 'quarter_fs/329020.csv' : 329020
object of type 'NoneType' has no len()
[2022-02-16 00:09] : (no_files, None) #2477 / 2491 rows > REPLACE INTO finance (99.43797671617824 %)[OK]
[Errno 2] No such file or directory: 'quarter_fs/216280.csv' : 216280
object of type 'NoneType' has no len()
[2022-02-16 00:09] : (no_files, None) #2478 / 2491 rows > REPLACE INTO finance (99.47812123645122 %)[OK]
[Errno 2] No such file or directory: 'quarter_fs/122830.csv' : 122830
object of type 'NoneType' has no len()
[2022-02-16 00:09] : (no_files, None) #2479 / 2491 rows > REPLACE INTO finance (99.5182657567242 %)[OK]
[Errno 2] No such file or directory: 'quarter_fs/140660.csv' : 140660
object of type 'NoneType' has no len()
[2022-02-16 00:09] : (no_files, None) #2480 / 2491 rows > REPLACE INTO finance (99.5584102769972 %)[OK]
[Errno 2] No such file or directory: 'quarter_fs/232530.csv' : 232530
object of type 'NoneType' has no len()
[2022-02-16 00:09] : (no_files, None) #2481 / 2491 rows > REPLACE INTO finance (99.59855479727018 %)[OK]
[Errno 2] No such file or directory: 'quarter_fs/299480.csv' : 299480
object of type 'NoneType' has no len()
[2022-02-16 00:09] : (no_files, None) #2482 / 2491 rows > REPLACE INTO finance (99.63869931754316 %)[OK]
[Errno 2] No such file or directory: 'quarter_fs/327970.csv' : 327970
object of type 'NoneType' has no len()
[2022-02-16 00:09] : (no_files, None) #2483 / 2491 rows > REPLACE INTO finance (99.67884383781613 %)[OK]
[Errno 2] No such file or directory: 'quarter_fs/189350.csv' : 189350
object of type 'NoneType' has no len()
[2022-02-16 00:09] : (no_files, None) #2484 / 2491 rows > REPLACE INTO finance (99.71898835808912 %)[OK]
[Errno 2] No such file or directory: 'quarter_fs/169670.csv' : 169670
object of type 'NoneType' has no len()
[2022-02-16 00:09] : (no_files, None) #2485 / 2491 rows > REPLACE INTO finance (99.7591328783621 %)[OK]
[Errno 2] No such file or directory: 'quarter_fs/318660.csv' : 318660
object of type 'NoneType' has no len()
[2022-02-16 00:09] : (no_files, None) #2486 / 2491 rows > REPLACE INTO finance (99.79927739863508 %)[OK]
[Errno 2] No such file or directory: 'quarter_fs/393210.csv' : 393210
object of type 'NoneType' has no len()
[2022-02-16 00:09] : (no_files, None) #2487 / 2491 rows > REPLACE INTO finance (99.83942191890807 %)[OK]
[Errno 2] No such file or directory: 'quarter_fs/217880.csv' : 217880
object of type 'NoneType' has no len()
[2022-02-16 00:09] : (no_files, None) #2488 / 2491 rows > REPLACE INTO finance (99.87956643918106 %)[OK]
[Errno 2] No such file or directory: 'quarter_fs/222670.csv' : 222670
object of type 'NoneType' has no len()
[2022-02-16 00:09] : (no_files, None) #2489 / 2491 rows > REPLACE INTO finance (99.91971095945404 %)[OK]
[Errno 2] No such file or directory: 'quarter_fs/331660.csv' : 331660
object of type 'NoneType' has no len()
[2022-02-16 00:09] : (no_files, None) #2490 / 2491 rows > REPLACE INTO finance (99.95985547972703 %)[OK]
[Errno 2] No such file or directory: 'quarter_fs/212310.csv' : 212310
object of type 'NoneType' has no len()

[12:13](https://w1642058681-uyn694772.slack.com/archives/D02TX49QRL4/p1644937993984929)
[Errno 2] No such file or directory: 'quarter_fs/288490.csv' Pandas(Index=2471, ID=2471, Symbol='288490')
[Errno 2] No such file or directory: 'quarter_fs/176750.csv' Pandas(Index=2472, ID=2472, Symbol='176750')
[Errno 2] No such file or directory: 'quarter_fs/224810.csv' Pandas(Index=2473, ID=2473, Symbol='224810')
[Errno 2] No such file or directory: 'quarter_fs/224020.csv' Pandas(Index=2474, ID=2474, Symbol='224020')
[Errno 2] No such file or directory: 'quarter_fs/207490.csv' Pandas(Index=2475, ID=2475, Symbol='207490')
[Errno 2] No such file or directory: 'quarter_fs/329020.csv' Pandas(Index=2476, ID=2476, Symbol='329020')
[Errno 2] No such file or directory: 'quarter_fs/216280.csv' Pandas(Index=2477, ID=2477, Symbol='216280')
[Errno 2] No such file or directory: 'quarter_fs/122830.csv' Pandas(Index=2478, ID=2478, Symbol='122830')
[Errno 2] No such file or directory: 'quarter_fs/140660.csv' Pandas(Index=2479, ID=2479, Symbol='140660')
[Errno 2] No such file or directory: 'quarter_fs/232530.csv' Pandas(Index=2480, ID=2480, Symbol='232530')
[Errno 2] No such file or directory: 'quarter_fs/299480.csv' Pandas(Index=2481, ID=2481, Symbol='299480')
[Errno 2] No such file or directory: 'quarter_fs/327970.csv' Pandas(Index=2482, ID=2482, Symbol='327970')
[Errno 2] No such file or directory: 'quarter_fs/189350.csv' Pandas(Index=2483, ID=2483, Symbol='189350')
[Errno 2] No such file or directory: 'quarter_fs/169670.csv' Pandas(Index=2484, ID=2484, Symbol='169670')
[Errno 2] No such file or directory: 'quarter_fs/318660.csv' Pandas(Index=2485, ID=2485, Symbol='318660')
[Errno 2] No such file or directory: 'quarter_fs/393210.csv' Pandas(Index=2486, ID=2486, Symbol='393210')
[Errno 2] No such file or directory: 'quarter_fs/217880.csv' Pandas(Index=2487, ID=2487, Symbol='217880')
[Errno 2] No such file or directory: 'quarter_fs/222670.csv' Pandas(Index=2488, ID=2488, Symbol='222670')
[Errno 2] No such file or directory: 'quarter_fs/331660.csv' Pandas(Index=2489, ID=2489, Symbol='331660')
[Errno 2] No such file or directory: 'quarter_fs/212310.csv' Pandas(Index=2490, ID=2490, Symbol='212310')
[12:13](https://w1642058681-uyn694772.slack.com/archives/D02TX49QRL4/p1644938005046359)
[Errno 2] No such file or directory: 'quarter_fs/257990.csv' Pandas(Index=2133, ID=2133, Symbol='257990')
[Errno 2] No such file or directory: 'quarter_fs/229500.csv' Pandas(Index=2134, ID=2134, Symbol='229500')
[Errno 2] No such file or directory: 'quarter_fs/178600.csv' Pandas(Index=2135, ID=2135, Symbol='178600')
[Errno 2] No such file or directory: 'quarter_fs/302920.csv' Pandas(Index=2136, ID=2136, Symbol='302920')
[Errno 2] No such file or directory: 'quarter_fs/253610.csv' Pandas(Index=2137, ID=2137, Symbol='253610')
[Errno 2] No such file or directory: 'quarter_fs/206950.csv' Pandas(Index=2138, ID=2138, Symbol='206950')
[Errno 2] No such file or directory: 'quarter_fs/148780.csv' Pandas(Index=2139, ID=2139, Symbol='148780')
[Errno 2] No such file or directory: 'quarter_fs/266170.csv' Pandas(Index=2140, ID=2140, Symbol='266170')
[Errno 2] No such file or directory: 'quarter_fs/260870.csv' Pandas(Index=2141, ID=2141, Symbol='260870')
[Errno 2] No such file or directory: 'quarter_fs/232830.csv' Pandas(Index=2142, ID=2142, Symbol='232830')
[Errno 2] No such file or directory: 'quarter_fs/286000.csv' Pandas(Index=2143, ID=2143, Symbol='286000')
[Errno 2] No such file or directory: 'quarter_fs/086460.csv' Pandas(Index=2144, ID=2144, Symbol='086460')
[Errno 2] No such file or directory: 'quarter_fs/140610.csv' Pandas(Index=2145, ID=2145, Symbol='140610')
[Errno 2] No such file or directory: 'quarter_fs/225860.csv' Pandas(Index=2146, ID=2146, Symbol='225860')
[Errno 2] No such file or directory: 'quarter_fs/216400.csv' Pandas(Index=2147, ID=2147, Symbol='216400')
[Errno 2] No such file or directory: 'quarter_fs/240340.csv' Pandas(Index=2148, ID=2148, Symbol='240340')
[Errno 2] No such file or directory: 'quarter_fs/233990.csv' Pandas(Index=2149, ID=2149, Symbol='233990')
[Errno 2] No such file or directory: 'quarter_fs/402420.csv' Pandas(Index=2150, ID=2150, Symbol='402420')
[Errno 2] No such file or directory: 'quarter_fs/215570.csv' Pandas(Index=2151, ID=2151, Symbol='215570')
[Errno 2] No such file or directory: 'quarter_fs/217950.csv' Pandas(Index=2152, ID=2152, Symbol='217950')
[Errno 2] No such file or directory: 'quarter_fs/202960.csv' Pandas(Index=2153, ID=2153, Symbol='202960')
[Errno 2] No such file or directory: 'quarter_fs/150440.csv' Pandas(Index=2154, ID=2154, Symbol='150440')
[12:13](https://w1642058681-uyn694772.slack.com/archives/D02TX49QRL4/p1644938017076209)
[Errno 2] No such file or directory: 'quarter_fs/348840.csv' Pandas(Index=1840, ID=1840, Symbol='348840')
[Errno 2] No such file or directory: 'quarter_fs/285770.csv' Pandas(Index=1841, ID=1841, Symbol='285770')
[Errno 2] No such file or directory: 'quarter_fs/179720.csv' Pandas(Index=1842, ID=1842, Symbol='179720')
[Errno 2] No such file or directory: 'quarter_fs/238500.csv' Pandas(Index=1843, ID=1843, Symbol='238500')
[Errno 2] No such file or directory: 'quarter_fs/267060.csv' Pandas(Index=1844, ID=1844, Symbol='267060')
[Errno 2] No such file or directory: 'quarter_fs/208890.csv' Pandas(Index=1845, ID=1845, Symbol='208890')
[Errno 2] No such file or directory: 'quarter_fs/266470.csv' Pandas(Index=1846, ID=1846, Symbol='266470')
[Errno 2] No such file or directory: 'quarter_fs/322190.csv' Pandas(Index=1847, ID=1847, Symbol='322190')
[Errno 2] No such file or directory: 'quarter_fs/258250.csv' Pandas(Index=1848, ID=1848, Symbol='258250')
[Errno 2] No such file or directory: 'quarter_fs/185190.csv' Pandas(Index=1849, ID=1849, Symbol='185190')
[Errno 2] No such file or directory: 'quarter_fs/258540.csv' Pandas(Index=1850, ID=1850, Symbol='258540')
[Errno 2] No such file or directory: 'quarter_fs/299670.csv' Pandas(Index=1851, ID=1851, Symbol='299670')
[Errno 2] No such file or directory: 'quarter_fs/234070.csv' Pandas(Index=1852, ID=1852, Symbol='234070')
[Errno 2] No such file or directory: 'quarter_fs/403360.csv' Pandas(Index=1853, ID=1853, Symbol='403360')
[Errno 2] No such file or directory: 'quarter_fs/121060.csv' Pandas(Index=1854, ID=1854, Symbol='121060')
[Errno 2] No such file or directory: 'quarter_fs/344860.csv' Pandas(Index=1855, ID=1855, Symbol='344860')
[Errno 2] No such file or directory: 'quarter_fs/379390.csv' Pandas(Index=1856, ID=1856, Symbol='379390')
[Errno 2] No such file or directory: 'quarter_fs/066830.csv' Pandas(Index=1857, ID=1857, Symbol='066830')
[Errno 2] No such file or directory: 'quarter_fs/180060.csv' Pandas(Index=1858, ID=1858, Symbol='180060')
[Errno 2] No such file or directory: 'quarter_fs/266870.csv' Pandas(Index=1859, ID=1859, Symbol='266870')
[12:13](https://w1642058681-uyn694772.slack.com/archives/D02TX49QRL4/p1644938026950349)
[Errno 2] No such file or directory: 'quarter_fs/278990.csv' Pandas(Index=1541, ID=1541, Symbol='278990')
[Errno 2] No such file or directory: 'quarter_fs/183410.csv' Pandas(Index=1542, ID=1542, Symbol='183410')
[Errno 2] No such file or directory: 'quarter_fs/086220.csv' Pandas(Index=1543, ID=1543, Symbol='086220')
[Errno 2] No such file or directory: 'quarter_fs/199150.csv' Pandas(Index=1544, ID=1544, Symbol='199150')
[Errno 2] No such file or directory: 'quarter_fs/162120.csv' Pandas(Index=1545, ID=1545, Symbol='162120')
[Errno 2] No such file or directory: 'quarter_fs/236340.csv' Pandas(Index=1546, ID=1546, Symbol='236340')
[Errno 2] No such file or directory: 'quarter_fs/191600.csv' Pandas(Index=1547, ID=1547, Symbol='191600')
[Errno 2] No such file or directory: 'quarter_fs/215050.csv' Pandas(Index=1548, ID=1548, Symbol='215050')
[Errno 2] No such file or directory: 'quarter_fs/149010.csv' Pandas(Index=1549, ID=1549, Symbol='149010')
[Errno 2] No such file or directory: 'quarter_fs/246250.csv' Pandas(Index=1550, ID=1550, Symbol='246250')
[Errno 2] No such file or directory: 'quarter_fs/093510.csv' Pandas(Index=1551, ID=1551, Symbol='093510')
[Errno 2] No such file or directory: 'quarter_fs/337840.csv' Pandas(Index=1552, ID=1552, Symbol='337840')
[Errno 2] No such file or directory: 'quarter_fs/208850.csv' Pandas(Index=1553, ID=1553, Symbol='208850')
[Errno 2] No such file or directory: 'quarter_fs/248020.csv' Pandas(Index=1554, ID=1554, Symbol='248020')
[Errno 2] No such file or directory: 'quarter_fs/140290.csv' Pandas(Index=1555, ID=1555, Symbol='140290')
[Errno 2] No such file or directory: 'quarter_fs/303360.csv' Pandas(Index=1556, ID=1556, Symbol='303360')
[Errno 2] No such file or directory: 'quarter_fs/242350.csv' Pandas(Index=1557, ID=1557, Symbol='242350')
[12:13](https://w1642058681-uyn694772.slack.com/archives/D02TX49QRL4/p1644938035536089)
[Errno 2] No such file or directory: 'quarter_fs/227420.csv' Pandas(Index=1215, ID=1215, Symbol='227420')
[Errno 2] No such file or directory: 'quarter_fs/163430.csv' Pandas(Index=1216, ID=1216, Symbol='163430')
[Errno 2] No such file or directory: 'quarter_fs/200580.csv' Pandas(Index=1217, ID=1217, Symbol='200580')
[Errno 2] No such file or directory: 'quarter_fs/210120.csv' Pandas(Index=1218, ID=1218, Symbol='210120')
[Errno 2] No such file or directory: 'quarter_fs/217320.csv' Pandas(Index=1219, ID=1219, Symbol='217320')
[Errno 2] No such file or directory: 'quarter_fs/236030.csv' Pandas(Index=1220, ID=1220, Symbol='236030')
[Errno 2] No such file or directory: 'quarter_fs/149300.csv' Pandas(Index=1221, ID=1221, Symbol='149300')
[Errno 2] No such file or directory: 'quarter_fs/251280.csv' Pandas(Index=1222, ID=1222, Symbol='251280')
[Errno 2] No such file or directory: 'quarter_fs/238170.csv' Pandas(Index=1223, ID=1223, Symbol='238170')
[Errno 2] No such file or directory: 'quarter_fs/224760.csv' Pandas(Index=1224, ID=1224, Symbol='224760')
[Errno 2] No such file or directory: 'quarter_fs/311060.csv' Pandas(Index=1225, ID=1225, Symbol='311060')
[Errno 2] No such file or directory: 'quarter_fs/084440.csv' Pandas(Index=1226, ID=1226, Symbol='084440')
[Errno 2] No such file or directory: 'quarter_fs/341310.csv' Pandas(Index=1227, ID=1227, Symbol='341310')
[Errno 2] No such file or directory: 'quarter_fs/135160.csv' Pandas(Index=1228, ID=1228, Symbol='135160')
[12:14](https://w1642058681-uyn694772.slack.com/archives/D02TX49QRL4/p1644938045595729)
[Errno 2] No such file or directory: 'quarter_fs/112190.csv' Pandas(Index=901, ID=901, Symbol='112190')
[Errno 2] No such file or directory: 'quarter_fs/092590.csv' Pandas(Index=902, ID=902, Symbol='092590')
[Errno 2] No such file or directory: 'quarter_fs/322970.csv' Pandas(Index=903, ID=903, Symbol='322970')
[Errno 2] No such file or directory: 'quarter_fs/245450.csv' Pandas(Index=904, ID=904, Symbol='245450')
[Errno 2] No such file or directory: 'quarter_fs/217910.csv' Pandas(Index=905, ID=905, Symbol='217910')
[Errno 2] No such file or directory: 'quarter_fs/270020.csv' Pandas(Index=906, ID=906, Symbol='270020')
[Errno 2] No such file or directory: 'quarter_fs/211050.csv' Pandas(Index=907, ID=907, Symbol='211050')
[Errno 2] No such file or directory: 'quarter_fs/116100.csv' Pandas(Index=908, ID=908, Symbol='116100')
[Errno 2] No such file or directory: 'quarter_fs/107640.csv' Pandas(Index=909, ID=909, Symbol='107640')
[12:14](https://w1642058681-uyn694772.slack.com/archives/D02TX49QRL4/p1644938054248689)
[Errno 2] No such file or directory: 'quarter_fs/317860.csv' Pandas(Index=594, ID=594, Symbol='317860')
[Errno 2] No such file or directory: 'quarter_fs/343090.csv' Pandas(Index=595, ID=595, Symbol='343090')
[Errno 2] No such file or directory: 'quarter_fs/114920.csv' Pandas(Index=596, ID=596, Symbol='114920')
[Errno 2] No such file or directory: 'quarter_fs/233250.csv' Pandas(Index=597, ID=597, Symbol='233250')
[Errno 2] No such file or directory: 'quarter_fs/225850.csv' Pandas(Index=598, ID=598, Symbol='225850')
[Errno 2] No such file or directory: 'quarter_fs/281310.csv' Pandas(Index=599, ID=599, Symbol='281310')
[Errno 2] No such file or directory: 'quarter_fs/199290.csv' Pandas(Index=600, ID=600, Symbol='199290')
[Errno 2] No such file or directory: 'quarter_fs/267810.csv' Pandas(Index=601, ID=601, Symbol='267810')
[Errno 2] No such file or directory: 'quarter_fs/044990.csv' Pandas(Index=602, ID=602, Symbol='044990')
[Errno 2] No such file or directory: 'quarter_fs/279060.csv' Pandas(Index=603, ID=603, Symbol='279060')
[Errno 2] No such file or directory: 'quarter_fs/254160.csv' Pandas(Index=604, ID=604, Symbol='254160')
[Errno 2] No such file or directory: 'quarter_fs/308700.csv' Pandas(Index=605, ID=605, Symbol='308700')
[Errno 2] No such file or directory: 'quarter_fs/258050.csv' Pandas(Index=606, ID=606, Symbol='258050')
[Errno 2] No such file or directory: 'quarter_fs/327610.csv' Pandas(Index=607, ID=607, Symbol='327610')
[12:14](https://w1642058681-uyn694772.slack.com/archives/D02TX49QRL4/p1644938062432909)
[Errno 2] No such file or directory: 'quarter_fs/076340.csv' Pandas(Index=289, ID=289, Symbol='076340')
[Errno 2] No such file or directory: 'quarter_fs/243870.csv' Pandas(Index=290, ID=290, Symbol='243870')
[Errno 2] No such file or directory: 'quarter_fs/244880.csv' Pandas(Index=291, ID=291, Symbol='244880')
[Errno 2] No such file or directory: 'quarter_fs/323350.csv' Pandas(Index=292, ID=292, Symbol='323350')
[Errno 2] No such file or directory: 'quarter_fs/271850.csv' Pandas(Index=293, ID=293, Symbol='271850')
[Errno 2] No such file or directory: 'quarter_fs/223220.csv' Pandas(Index=294, ID=294, Symbol='223220')
[Errno 2] No such file or directory: 'quarter_fs/067370.csv' Pandas(Index=295, ID=295, Symbol='067370')
[Errno 2] No such file or directory: 'quarter_fs/103660.csv' Pandas(Index=296, ID=296, Symbol='103660')
[Errno 2] No such file or directory: 'quarter_fs/270210.csv' Pandas(Index=297, ID=297, Symbol='270210')
[Errno 2] No such file or directory: 'quarter_fs/276240.csv' Pandas(Index=298, ID=298, Symbol='276240')
[Errno 2] No such file or directory: 'quarter_fs/221800.csv' Pandas(Index=299, ID=299, Symbol='221800')
[Errno 2] No such file or directory: 'quarter_fs/250030.csv' Pandas(Index=300, ID=300, Symbol='250030')
[Errno 2] No such file or directory: 'quarter_fs/136660.csv' Pandas(Index=301, ID=301, Symbol='136660')
[Errno 2] No such file or directory: 'quarter_fs/336040.csv' Pandas(Index=302, ID=302, Symbol='336040')
[Errno 2] No such file or directory: 'quarter_fs/309900.csv' Pandas(Index=303, ID=303, Symbol='309900')

**Comment by aLVINlEE9** [comment]
네이버 금융에서 konex의 재무재표 자료가 없어서 csv파일자체가 없어서 exception으로 처리해두었습니다.
