### ISSUE TITLE
price table 데이터 손실

### ISSUE THREAD

**Issue by Jinseok-Heo** [economicus/finance_data#9]
1995~1996-07-01 사이의 데이터가 테이블에 들어가지 않습니다.

**Comment by aLVINlEE9** [comment]
price 데이터는 marcap_data(최대 1995-05-02부터) 와 fdr.DataReader(최대 1998-01-07부터) 데이터 둘을 합친거라서 실제 데이터는 1998년 data부터 시작될것입니다.
